export type JournalEntry = {
  id: string;
  title: string;
  author: string;
  date: string;
  summary: string;
  body: string[];
  stations: string[];
  photos: { id: string; label: string }[];
};

export const journalEntries: JournalEntry[] = [
  {
    id: "1",
    title: "점검표준 대비 시설점검",
    author: "관리자",
    date: "2025-12-30",
    summary: "16:00 기준 수위 3.21 m 평상시 대비 +0.15",
    body: [
      "배수로, 유입부, 관측기 하우징 점검 완료.",
      "데이터 전송 이상 없음 확인.",
      "재난상황실 비상연락망 확인 완료.",
      "2025-11-12 오전 재점검 예정.",
    ],
    stations: ["양산시 양산교", "김해시 정천교", "부산시 구포대교"],
    photos: [
      { id: "photo-1", label: "현장 사진 1" },
      { id: "photo-2", label: "현장 사진 2" },
      { id: "photo-3", label: "현장 사진 3" },
    ],
  },
  {
    id: "2",
    title: "양산시 양산교 - 수위 관측기 설치",
    author: "관리자",
    date: "2025-11-10",
    summary: "신규 수위 관측기 설치 및 통신 테스트 완료.",
    body: [
      "센서 고정 브라켓 설치 완료.",
      "전원 및 통신 라인 연결 후 정상 송신 확인.",
      "현장 담당자 교육 진행.",
    ],
    stations: ["양산시 양산교"],
    photos: [
      { id: "photo-1", label: "현장 사진 1" },
      { id: "photo-2", label: "현장 사진 2" },
      { id: "photo-3", label: "현장 사진 3" },
    ],
  },
  {
    id: "3",
    title: "김해시 정천교 - 배수로 점검",
    author: "관리자",
    date: "2025-11-09",
    summary: "우기 대비 배수로 이물질 제거.",
    body: [
      "배수로 상류 구간 청소 완료.",
      "펌프실 누수 여부 확인.",
      "다음 점검 일정: 2025-11-20.",
    ],
    stations: ["김해시 정천교"],
    photos: [
      { id: "photo-1", label: "현장 사진 1" },
      { id: "photo-2", label: "현장 사진 2" },
      { id: "photo-3", label: "현장 사진 3" },
    ],
  },
  {
    id: "4",
    title: "점검표준 대비 시설점검",
    author: "관리자",
    date: "2025-11-08",
    summary: "관측소 하우징 상태 양호.",
    body: [
      "전원 상태 정상.",
      "통신 장비 상태 정상.",
      "CCTV 시야 확보 완료.",
    ],
    stations: ["부산시 구포대교"],
    photos: [
      { id: "photo-1", label: "현장 사진 1" },
      { id: "photo-2", label: "현장 사진 2" },
      { id: "photo-3", label: "현장 사진 3" },
    ],
  },
  {
    id: "5",
    title: "양산시 양산교 - 수위 관측기 설치",
    author: "관리자",
    date: "2025-11-07",
    summary: "센서 초기값 보정 완료.",
    body: [
      "초기값 보정 후 기준값 저장.",
      "알람 임계값 설정 완료.",
    ],
    stations: ["양산시 양산교"],
    photos: [
      { id: "photo-1", label: "현장 사진 1" },
      { id: "photo-2", label: "현장 사진 2" },
      { id: "photo-3", label: "현장 사진 3" },
    ],
  },
  {
    id: "6",
    title: "김해시 정천교 - 배수로 점검",
    author: "관리자",
    date: "2025-11-06",
    summary: "배수로 상태 확인 및 청소.",
    body: ["하류 구간 이물질 제거.", "배수로 벽면 균열 없음."],
    stations: ["김해시 정천교"],
    photos: [
      { id: "photo-1", label: "현장 사진 1" },
      { id: "photo-2", label: "현장 사진 2" },
      { id: "photo-3", label: "현장 사진 3" },
    ],
  },
  {
    id: "7",
    title: "점검표준 대비 시설점검",
    author: "관리자",
    date: "2025-11-05",
    summary: "정기 점검 완료.",
    body: ["관측 장비 정상 동작 확인.", "현장 청결 상태 양호."],
    stations: ["부산시 구포대교"],
    photos: [
      { id: "photo-1", label: "현장 사진 1" },
      { id: "photo-2", label: "현장 사진 2" },
      { id: "photo-3", label: "현장 사진 3" },
    ],
  },
  {
    id: "8",
    title: "양산시 양산교 - 수위 관측기 설치",
    author: "관리자",
    date: "2025-11-04",
    summary: "통신 모듈 교체 완료.",
    body: ["통신 모듈 교체 후 신호 강도 개선."],
    stations: ["양산시 양산교"],
    photos: [
      { id: "photo-1", label: "현장 사진 1" },
      { id: "photo-2", label: "현장 사진 2" },
      { id: "photo-3", label: "현장 사진 3" },
    ],
  },
  {
    id: "9",
    title: "김해시 정천교 - 배수로 점검",
    author: "관리자",
    date: "2025-11-03",
    summary: "배수로 상태 양호.",
    body: ["우기 대비 점검 완료."],
    stations: ["김해시 정천교"],
    photos: [
      { id: "photo-1", label: "현장 사진 1" },
      { id: "photo-2", label: "현장 사진 2" },
      { id: "photo-3", label: "현장 사진 3" },
    ],
  },
  {
    id: "10",
    title: "김해시 정천교 - 배수로 점검",
    author: "관리자",
    date: "2025-11-01",
    summary: "배수로 점검 및 기록.",
    body: ["장비 상태 양호 확인."],
    stations: ["김해시 정천교"],
    photos: [
      { id: "photo-1", label: "현장 사진 1" },
      { id: "photo-2", label: "현장 사진 2" },
      { id: "photo-3", label: "현장 사진 3" },
    ],
  },
  {
    id: "11",
    title: "하구 합류점 점검 기록",
    author: "관리자",
    date: "2025-10-28",
    summary: "하구 합류점 수위 변화 기록.",
    body: ["수위 변화 및 조석 영향 기록."],
    stations: ["부산시 구포대교"],
    photos: [
      { id: "photo-1", label: "현장 사진 1" },
      { id: "photo-2", label: "현장 사진 2" },
      { id: "photo-3", label: "현장 사진 3" },
    ],
  },
  {
    id: "12",
    title: "센서 교체 및 보정",
    author: "관리자",
    date: "2025-10-24",
    summary: "수위 센서 교체 후 보정 완료.",
    body: ["교체 후 초기값 보정 및 테스트 완료."],
    stations: ["양산시 양산교"],
    photos: [
      { id: "photo-1", label: "현장 사진 1" },
      { id: "photo-2", label: "현장 사진 2" },
      { id: "photo-3", label: "현장 사진 3" },
    ],
  },
  {
    id: "13",
    title: "전원 장치 정기 점검",
    author: "관리자",
    date: "2025-10-20",
    summary: "전원 장치 상태 점검 및 정리.",
    body: ["배터리 상태 점검.", "충전 장치 점검."],
    stations: ["김해시 정천교"],
    photos: [
      { id: "photo-1", label: "현장 사진 1" },
      { id: "photo-2", label: "현장 사진 2" },
      { id: "photo-3", label: "현장 사진 3" },
    ],
  },
  {
    id: "14",
    title: "현장 출입로 정비",
    author: "관리자",
    date: "2025-10-18",
    summary: "출입로 안전 시설 점검.",
    body: ["난간 점검.", "경고 표지 정리."],
    stations: ["부산시 구포대교"],
    photos: [
      { id: "photo-1", label: "현장 사진 1" },
      { id: "photo-2", label: "현장 사진 2" },
      { id: "photo-3", label: "현장 사진 3" },
    ],
  },
  {
    id: "15",
    title: "관측소 장비 청소",
    author: "관리자",
    date: "2025-10-15",
    summary: "장비 외관 청소 및 점검.",
    body: ["센서 오염 확인.", "외관 청소 완료."],
    stations: ["양산시 양산교"],
    photos: [
      { id: "photo-1", label: "현장 사진 1" },
      { id: "photo-2", label: "현장 사진 2" },
      { id: "photo-3", label: "현장 사진 3" },
    ],
  },
  {
    id: "16",
    title: "통신 상태 점검",
    author: "관리자",
    date: "2025-10-12",
    summary: "통신 상태 정상 확인.",
    body: ["LTE 신호 강도 점검.", "데이터 전송 확인."],
    stations: ["김해시 정천교"],
    photos: [
      { id: "photo-1", label: "현장 사진 1" },
      { id: "photo-2", label: "현장 사진 2" },
      { id: "photo-3", label: "현장 사진 3" },
    ],
  },
  {
    id: "17",
    title: "우기 대비 시설 점검",
    author: "관리자",
    date: "2025-10-10",
    summary: "우기 대비 점검 완료.",
    body: ["배수로 청소.", "관측기 하우징 점검."],
    stations: ["부산시 구포대교"],
    photos: [
      { id: "photo-1", label: "현장 사진 1" },
      { id: "photo-2", label: "현장 사진 2" },
      { id: "photo-3", label: "현장 사진 3" },
    ],
  },
  {
    id: "18",
    title: "유량 측정 기록",
    author: "관리자",
    date: "2025-10-07",
    summary: "유량 측정 및 기록 완료.",
    body: ["유량 측정 완료.", "기록 저장."],
    stations: ["김해시 정천교"],
    photos: [
      { id: "photo-1", label: "현장 사진 1" },
      { id: "photo-2", label: "현장 사진 2" },
      { id: "photo-3", label: "현장 사진 3" },
    ],
  },
  {
    id: "19",
    title: "안전 점검 체크리스트",
    author: "관리자",
    date: "2025-10-03",
    summary: "안전 점검 체크리스트 완료.",
    body: ["안전 장비 점검.", "경고 표지 확인."],
    stations: ["부산시 구포대교"],
    photos: [
      { id: "photo-1", label: "현장 사진 1" },
      { id: "photo-2", label: "현장 사진 2" },
      { id: "photo-3", label: "현장 사진 3" },
    ],
  },
  {
    id: "20",
    title: "관측 장비 테스트",
    author: "관리자",
    date: "2025-09-29",
    summary: "관측 장비 성능 테스트.",
    body: ["테스트 결과 정상.", "데이터 수집 확인."],
    stations: ["양산시 양산교"],
    photos: [
      { id: "photo-1", label: "현장 사진 1" },
      { id: "photo-2", label: "현장 사진 2" },
      { id: "photo-3", label: "현장 사진 3" },
    ],
  },
  {
    id: "21",
    title: "정기 점검 보고",
    author: "관리자",
    date: "2025-09-25",
    summary: "정기 점검 보고서 작성.",
    body: ["점검 결과 기록.", "후속 조치 필요 사항 정리."],
    stations: ["김해시 정천교"],
    photos: [
      { id: "photo-1", label: "현장 사진 1" },
      { id: "photo-2", label: "현장 사진 2" },
      { id: "photo-3", label: "현장 사진 3" },
    ],
  },
  {
    id: "22",
    title: "예비 장비 점검",
    author: "관리자",
    date: "2025-09-21",
    summary: "예비 장비 상태 점검 완료.",
    body: ["예비 센서 점검.", "보관 상태 확인."],
    stations: ["부산시 구포대교"],
    photos: [
      { id: "photo-1", label: "현장 사진 1" },
      { id: "photo-2", label: "현장 사진 2" },
      { id: "photo-3", label: "현장 사진 3" },
    ],
  },
  {
    id: "23",
    title: "현장 안전 교육",
    author: "관리자",
    date: "2025-09-18",
    summary: "현장 안전 교육 진행.",
    body: ["안전 교육 완료.", "참석자 기록."],
    stations: ["양산시 양산교"],
    photos: [
      { id: "photo-1", label: "현장 사진 1" },
      { id: "photo-2", label: "현장 사진 2" },
      { id: "photo-3", label: "현장 사진 3" },
    ],
  },
  {
    id: "24",
    title: "장비 교정 기록",
    author: "관리자",
    date: "2025-09-14",
    summary: "장비 교정 기록 작성.",
    body: ["교정 기록 저장.", "다음 교정 일정 확보."],
    stations: ["김해시 정천교"],
    photos: [
      { id: "photo-1", label: "현장 사진 1" },
      { id: "photo-2", label: "현장 사진 2" },
      { id: "photo-3", label: "현장 사진 3" },
    ],
  },
  {
    id: "25",
    title: "관측소 주변 정리",
    author: "관리자",
    date: "2025-09-10",
    summary: "관측소 주변 정리 작업.",
    body: ["잡초 제거.", "접근로 정리."],
    stations: ["부산시 구포대교"],
    photos: [
      { id: "photo-1", label: "현장 사진 1" },
      { id: "photo-2", label: "현장 사진 2" },
      { id: "photo-3", label: "현장 사진 3" },
    ],
  },
];
